version: '3.8'

services:
  whisper-api:
    build:
      context: .
      dockerfile: Dockerfile
    image: yourusername/your-whisper-app
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - whisper_cache:/root/.cache/whisper 
    environment:
      WHISPER_MODEL: ${WHISPER_MODEL:-base}
      WHISPER_DEVICE: "cpu"


volumes:
  whisper_cache: 
    driver: local