version: '3.8'

services:
  whisper-api:
    build:
      context: .
      dockerfile: Dockerfile 
    restart: unless-stopped

    volumes:
      - whisper_cache:/root/.cache/whisper
    environment:
      MY_API_KEY: ${MY_API_KEY}
      WHISPER_MODEL: ${WHISPER_MODEL:-base}
      WHISPER_DEVICE: "cpu"

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]


  cloudflare:
    image: 'cloudflare/cloudflared:latest'
    restart: unless-stopped
    command: 'tunnel --no-autoupdate run'
    environment:
      TUNNEL_TOKEN: '${TUNNEL_TOKEN}'

volumes:
  whisper_cache: 
    driver: local