version: '3.8'

services:
  whisper-api:
    ports:
      - "8001:8000"
    build:
      context: .
      dockerfile: Dockerfile 
    restart: unless-stopped

    volumes:
      - whisper_cache:/root/.cache/whisper
    environment:
      WHISPER_MODEL: ${WHISPER_MODEL:-base}
      WHISPER_DEVICE: "cpu"

  cloudflare:
    image: 'cloudflare/cloudflared:latest'
    restart: unless-stopped
    command: 'tunnel --no-autoupdate run'
    environment:
      TUNNEL_TOKEN: '${TUNNEL_TOKEN}'

volumes:
  whisper_cache: 
    driver: local